### ISSUE TITLE
script error 

### ISSUE THREAD

**Issue by MCjorsh5** [ssrlive/toyvpn#2]
./run-server.sh: line 34: ifconfig: command not found
Failed run 'ifconfig ${TUN_NETWORK_DEV} 10.10.0.1 dstaddr 10.10.0.2 up', exiting...

**Comment by ssrlive** [comment]
```
sudo apt install net-tools -y
```

**Comment by MCjorsh5** [comment]
ioctl(TUNSETIFF): Device or resource busy
Failed run 'ip tuntap add dev ${TUN_NETWORK_DEV} mode tun', exiting...

**Comment by ssrlive** [comment]
well, reboot your server. and try again.

**Comment by MCjorsh5** [comment]
shared secret test?

the android client shows connect disconnected constantly what else is missing

my command : ./ToyVpnServer tun0 8000 test -m 1400 -a 10.10.0.2 32 -d 8.8.8.8 -r 0.0.0.0

**Comment by ssrlive** [comment]
yes, the secret is `test`, you can change it as you wish.

**Comment by MCjorsh5** [comment]
I don't get connection it shows repeatedly connecting disconnected, it doesn't get the connection and the server doesn't show any log.

**Comment by ssrlive** [comment]
server address is your host public IP. like `123.45.67.89`

**Comment by ssrlive** [comment]
note your server firewall settings. note it's UDP.

**Comment by MCjorsh5** [comment]
do you have telegram can i contact you?

**Comment by ssrlive** [comment]
ssrlive

**Comment by MCjorsh5** [comment]
It already worked for me, how can I contact you? I would like to make a modification to this project and pay you for doing this work. how can i contact you

https://t.me/MCjorsh send me

**Comment by ssrlive** [comment]
this project is sooooo simple. Not worthy to pay for it. My tg ID is
ssrlive, I’m try to write a VPN via TCP and using rust programming
language.

**Comment by MCjorsh5** [comment]
I can't find you on telegram =( some channels appear with that ID, no user with that name appears

**Comment by ssrlive** [comment]
realssrlive
